awscli: fix test
Fixes:
MethodDeprecatedError: Calling assert_include is deprecated! Use assert_includes instead.

Closes #22932.

Signed-off-by: Michka Popoff <3406519+iMichka@users.noreply.github.com>